version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies"
      - pip install --upgrade pip
      - pip install -r requirements.txt
      - echo "Checking Python version"
      - python --version
      - echo "Checking pip version"
      - pip --version
      - echo "Listing installed packages"
      - pip list
      - echo "Listing files"
      - ls -l
      - echo "Checking for train.py"
      - ls -l train.py
      - echo "Checking for Dockerfile"
      - ls -l dockerfile

  build:
    commands:
      - set -x  # Enable command tracing
      - echo "Training the weather prediction model"
      - python train.py  # Your script for training the LSTM model
      - echo "Model trained successfully"
      - echo "Building Docker image"
      - docker build -t streamlit-app . || { echo "Docker build failed"; exit 1; }
      - echo "Logging into ECR"
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 367499066414.dkr.ecr.us-east-1.amazonaws.com
      - echo "Tagging Docker image"
      - docker tag streamlit-app:latest 367499066414.dkr.ecr.us-east-1.amazonaws.com/weather_predictor:latest
      - echo "Pushing Docker image to ECR"
      - docker push 367499066414.dkr.ecr.us-east-1.amazonaws.com/weather_predictor:latest || { echo "Docker push failed"; exit 1; }

artifacts:
  files:
    - model_scripted.pt  # The packaged model file to be uploaded
