version: 0.2

phases:
  install:
    commands:
      - pip install --upgrade pip
      - pip install -r requirements.txt
      - python --version
      - pip --version
      - pip list
      - ls -l
      - ls -l train.py
      - ls -l dockerfile

  build:
    commands:
      - set -x  # Enable command tracing
      - python train.py  # Your script for training the LSTM model
      - docker build -t weatherpredictor:latest .
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/h0w6o2c0
      - docker tag weatherpredictor:latest public.ecr.aws/h0w6o2c0/weatherpredictor:latest
      - docker push public.ecr.aws/h0w6o2c0/weatherpredictor:latest
      - aws ssm send-command --instance-ids "i-06b79a4f1acd940c1" --document-name "AWS-RunShellScript" --comment "Running deploy.sh on EC2 instance" --parameters '{"commands":["sudo /home/ec2-user/deploy.sh"]}'

