version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Installing dependencies"
      - pip install --upgrade pip
      - pip install -r requirements.txt  # Ensure your dependencies are listed in a 'requirements.txt' file
  build:
    commands:
      - echo "Training the weather prediction model"
      - python train.py  # This is your script for training the LSTM model
      - echo "Model trained successfully"
artifacts:
  files:
    - model_scripted.pt  # The packaged model file to be uploaded
