[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false
staticUrlPath = "/static"
maxUploadSize = 1000
baseUrlPath = "/"

# Set the address that Streamlit binds to for listening to incoming requests
address = "0.0.0.0"

[logger]
level = "info"  # You can change it to "debug" if you need more verbose logs

[theme]
primaryColor = "blue"  # You can change the color, this is just an example
